export const GET_QUOTES_RESPONSE = 'GET_QUOTES_RESPONSE';
export const GET_QUOTE_RESPONSE = 'GET_QUOTE_RESPONSE';
export const ADD_NEW_QUOTE_RESPONSE = 'ADD_NEW_QUOTE_RESPONSE';
export const UPDATE_EXISTING_QUOTE_RESPONSE = 'UPDATE_EXISTING_QUOTE_RESPONSE';
export const DELETE_QUOTE_RESPONSE = 'DELETE_QUOTE_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
